
# language: cpp
# before_install: "./CI/install-dependencies-linux.sh"
# before_script: "./CI/before-script-linux.sh"
# script: cd ./build && make -j4 
# before_deploy: "./CI/before-deploy-linux.sh"

os: linux
language: python



python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  
# command to install dependencies
#install: "pip install -r requirements.txt"

# command to run tests
# script: nosetests  

