
# travis+git

# matrix:
 # include:
 
os: linux
sudo: required
dist: trusty
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
  
# env: DJANGO_VERSION=1.8.2

# fast_finish: true	
language: c

before_cache: rm -f $HOME/.cache/pip/log/debug.log
  
cache:


 pip: true
# timeout: 1000

 - ccache

 directories:
   - .autoconf
   - $HOME/.m2
   - $HOME/.cache/pip
   - $HOME/.pyenv
  # bundler: true
  
branches:
 only:
  - master
  - alpha
  
# command to install dependencies
# before_install: install-dependencies-linux.sh

install: 
 # - key
 # - pip install -r requirements.txt 
 # --user param if no sudo-access user
 # -q Django==$DJANGO_VERSION
 - sudo pip install RPi.GPIO
 - sudo apt-get install python-rpi.gpio
 - sudo python setup.py install
 # - virtualenv ./nodeps
 # - ./nodeps/bin/python setup.py install
 # - curl-config --version; pip freeze
 
notifications:
  email: false 

# command to run tests +scripts
# before_script: before-script-linux.sh

script:
# - key
  - nosetests
# - make test
  - sudo python pifunk-main.py
 # - sudo python pifunk-temp.py
 # - sudo python pifunk-cb.py
 # - sudo python pifunk-pmr.py
 # - sudo python pifm.py
 # - sudo python pifm.c
 # - sudo make pifm.c 
 # - cd ./silicator/PiFunk


# before_deploy: ./before-deploy-linux.sh

# deploy:
  # provider: releases
   # api_key:
    # secure: token-key
  # file: dist/*.py
  # file_glob: true
  # on:
    # repo: silicator/PiFunk
    # tags: true
  # skip_cleanup: true


  
  

# after_failure:
# after_success:
 # - coveralls
 # - coverage combine
 # - codecov

 