name: C/C++ CI

on: 
  push:
   branches: 
   - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: pifunk
      run: ./pifunk -h
    - name: make-piversion
      run: make piversion
