name: C/C++ CI

on: 
  push:
   branches: 
   - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    #- name: make piversion
    #   run: sudo make piversion
    
    #- name: make
    #   run: sudo make
      
    #- name: pifunk help
    #   run: sudo ./bin/pifunk -h

